#!/bin/bash

#                  _
#                /   \
#               |  o  |
#                \   /
#         ________) (________
#        |                   |
#        '------.     .------'
#                |   |
#                |   |
#                |   |
#                |   |
#     /\         |   |         /\
#    /_ \        /   \        / _\
#      \ '.    .'     '.    .' /
#       \  '--'         '--'  /
#        '.                 .'
#          '._           _.'
#             `'-.   .-'`
#                 \ /
#                  `
# Defines the active versions of apps, plugins (etc) as environment variables that are
# later used by wrappers inside ucore. The variables get defined by the convention
# $UVER_<NAME>_VERSION. They are declared using json files which can be localized
# under the "../versions" folder (the json structure is basically an one dimension object).
# Any json file created under ../versions is going to be used automatically.

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# at deployment time the contents of src are moved to the root of the version. Lets
# detect this behaviour first, otherwise it should fallback to the current structure
# where versions folder is localized under the root
# \todo: consider moving this version directory location to an environment
# variable ($UVER_VERSIONS_DIR)
versionsParentDir=$dir
if ! [ -d "$versionsParentDir/versions" ]; then
  versionsParentDir="$( dirname $versionsParentDir )"
fi

# sourcing scripts
# core versions (looping through the versions types apps, libraries... etc)
coreVersions=$(eval echo "$versionsParentDir/versions")
localVersions=$(eval echo "$UVER_LOCAL/versions")
if [ -d "$localVersions" ]; then
  localVersions=$localVersions
else
  localVersions=""
fi

# setting versions as environment variables
for coreVersionType in $coreVersions $localVersions; do
    while IFS='=' read -r name version || [[ -n "$name" ]];
    do
      # convention followed by UVER_<NAME>_VERSION=<VERSION>
      export "$name"=$version
    done < <($dir/uvervars $coreVersionType)
done
