#!/usr/bin/env python

import sys
import json
import argparse

def uqueryflatjson(versionFile, separator):
    """
    Outputs an one dimension json object in the stdout
    """
    with open(versionFile, 'r') as f:
        data = json.load(f)
        for key, value in data.iteritems():
            sys.stdout.write('{key}{separator}{value}\n'.format(key=key, separator=separator, value=value))

# command help
parser = argparse.ArgumentParser(description='UMedia: Outputs a one dimension json object')
parser.add_argument(
    'file',
    metavar='file',
    type=str,
    help='json file'
)

parser.add_argument(
    '--separator',
    metavar='s',
    default='=',
    type=str,
    help='separator to be used between the key and value'
)

if __name__ == "__main__":
    args = parser.parse_args()
    uqueryflatjson(args.file, args.separator)
