#!/usr/bin/env python

import os
import sys
import argparse
import uver

def outputVars(fileOrDirectory, separator):
    """
    Output the parsed uver var names followed by the version in the stream.
    """
    uverParser = None

    # parsing from a file
    if os.path.isfile(fileOrDirectory):
        uverParser = uver.Parser.JsonParser()
        with open(fileOrDirectory, 'r') as f:
            uverParser.addFromJson('\n'.join(f.readlines()))

    # parsing from a directory
    else:
        uverParser = uver.Parser.JsonDirectoryParser()
        uverParser.addFromJsonDirectory(fileOrDirectory)

    # oututing result to the stream
    for software in uverParser.softwares():
        sys.stdout.write('{key}{separator}{value}\n'.format(
            key=software.uverName(),
            separator=separator,
            value=software.version()
        ))


# command help
parser = argparse.ArgumentParser(
    description='Outputs the uver variables followed by their versions'
)

parser.add_argument(
    'fileordirectory',
    metavar='json',
    type=str,
    help='json file or directory containing json files'
)

parser.add_argument(
    '--separator',
    metavar='s',
    default='=',
    type=str,
    help='separator to be used between the key and value (default: "=")'
)

if __name__ == "__main__":
    args = parser.parse_args()
    outputVars(args.fileordirectory, args.separator)
